### ISSUE TITLE
Unable to register with new user

### ISSUE THREAD

**Issue by subhansu7119** [dkb007/BusTrackingProject#1]
Application closes automatically if i try to register for new user

**Comment by DKB0512** [comment]
This is my college project and the back-end database (Firebase) has been closed down. So if you want to Register or Login into the application, just create a new Firebase account and connect the Real-time database with this application.

**Comment by subhansu7119** [comment]
Even after changing it, error exists

**Comment by subhansu7119** [comment]
It got connected but while entering any credentials it is showing error

**Comment by subhansu7119** [comment]
Actually I manually entered the details then I was able to login. Can you
please tell me about map, routes etc in brief. It's really important for
me.

Thankyou

**Comment by DKB0512** [comment]
Can you provide error's screenshot or any other clues so I can get more info about it.

**Comment by subhansu7119** [comment]
When I'm registering through application it doesn't makes any entry in the
database. But if I do manually by going to firebase then I can login
through the application.
